version: '3.7'
services:
  remitano-be:
    image: "remitano-be"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remitano-be
    hostname: remitano-be
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - default
